deanery/app/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from app import views

urlpatterns = [
    path('', views.HomePageView.as_view()),
    path('login/', views.CustomLoginView.as_view()),
    path('logout/', auth_views.LogoutView.as_view()),
    path('register/', views.CustomRegisterView.as_view()),
    path('home/', views.HomePageView.as_view()),
    path('student/', views.StudentView.as_view()),
    path('teacher/', views.TeacherView.as_view()),
    path('mark/<int:pk>/', views.UpdateMark.as_view()),
    path('mark/add/', views.AddMark.as_view()),
    path('mark/<int:pk>/delete/', views.DeleteMark.as_view())
]

deanery/deanery/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls'))
]

deanery/app/models.py
from django.db import models
from django.contrib.auth.models import User, Group, Permission


MARKS_VALUES = (20, 30, 35, 40, 45, 50)
MARKS_DISPLAY = ('2.0', '3.0', '3.5', '4.0', '4.5', '5.0')


class Subject(models.Model):
    name = models.CharField(
        unique=True,
        max_length=30
    )


class Person(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.SET_NULL,
        blank=True,
        null=True
    )
    subjects = models.ManyToManyField(Subject)

    class Meta:
        abstract = True


class Student(Person):
    pass


class Teacher(Person):
    pass


class Assignment(models.Model):
    name = models.CharField(
        max_length=30,
        null=True,
    )
    subject = models.ForeignKey(
        Subject,
        on_delete=models.DO_NOTHING
    )


class Mark(models.Model):
    subject = models.ForeignKey(
        Subject,
        on_delete=models.DO_NOTHING
    )
    assignment = models.ForeignKey(
        Assignment,
        on_delete=models.DO_NOTHING
    )
    student = models.ForeignKey(
        Student,
        on_delete=models.DO_NOTHING
    )
    value = models.PositiveSmallIntegerField(
        choices=tuple(zip(MARKS_VALUES, MARKS_DISPLAY)),
        null=True
    )

deanery/app/templates/base.html
<!doctype html>

<html>
<head>
  {% block head %}
    <title> Deanery: {{ title }}</title>
    <link rel="stylesheet" href="/static/style.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css"
          integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp"
          crossorigin="anonymous">
  {% endblock %}
</head>
<body>
<header>
  {% block header %}
  {% endblock %}
</header>
<div class="content">
  {% block content %}
  {% endblock %}
</div>
</body>
</html>

deanery/app/templates/errors.html
{% extends "logged_in.html" %}

{% block content %}
  {% if form.errors %}
    {% for field in form %}
      {% for error in field.errors %}
        <div style="text-align: center; color: crimson; width: 450px; margin: 5px auto;">
          <b>{{ error|escape }}</b>
        </div>
      {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
      <div style="text-align: center; color: crimson; width: 450px; margin: 5px auto;">
        <b>{{ error|escape }}</b>
      </div>
    {% endfor %}
  {% endif %}
  <div style="text-align: center; width: 450px; margin: 5px auto;">
    <a href="/home/">Go back to homepage</a>
  </div>
{% endblock %}

deanery/app/templates/logged_in.html
{% extends "base.html" %}

{% block header %}
  {{ block.super }}
  <h2 style="position: absolute; left: 0; margin-left: 10px;">
    {{ full_name }}
  </h2>
  <nav>
    <ul>
      <li>
        <a href="/logout/">Log Out</a>
      </li>
    </ul>
  </nav>
{% endblock %}

deanery/app/templates/student.html
{% extends "logged_in.html" %}

{% block content %}
  {% for pair in subject_with_marks_list %}
    <div style="margin: 20px 10px;">
      <h3>{{ pair.subject.name }}</h3>
      <table>
        <tr>
          {% for mark in pair.marks %}
            <th>{{ mark.assignment.name }}</th>
          {% endfor %}
        </tr>
        <tr>
          {% for mark in pair.marks %}
            <td>{{ mark.get_value_display }}</td>
          {% endfor %}
        </tr>
      </table>
    </div>
  {% endfor %}
{% endblock %}

deanery/app/templates/teacher.html
{% extends "logged_in.html" %}

{% block content %}
  {% for subject in subjects %}
    <div style="margin: 20px 10px;">
      <h3>{{ subject.name }}</h3>
      <table class="teacher">
        <tr>
          <th></th>
          {% for assignment_name in subject.assignments %}
            <th>{{ assignment_name }}</th>
          {% endfor %}
        </tr>
        {% for student in subject.students %}
          <tr>
            <td>{{ student.full_name }}</td>
            {% for fm in student.fm %}
              <td class="mark">
                {% if fm.mark.value %}
                  <span class="markValue">{{ fm.mark.get_value_display }}</span>
                  <form name="update" method="post" action="/mark/{{ fm.mark.pk }}/">
                    {% csrf_token %}
                    {{ fm.form.subject }}
                    {{ fm.form.assignment }}
                    {{ fm.form.student }}
                    {{ fm.form.value }}
                    <button type="submit">
                      <i class="fa fa-save"></i>
                    </button>
                  </form>
                  <form name="delete" method="post" action="/mark/{{ fm.mark.pk }}/delete/">
                    {% csrf_token %}
                    {{ fm.form.subject }}
                    {{ fm.form.assignment }}
                    {{ fm.form.student }}
                    <div style="display: none;">
                      {{ fm.form.value }}
                    </div>
                    <button type="submit">
                      <i class="fa fa-trash-alt"></i>
                    </button>
                  </form>
                {% else %}
                  <form name="add" method="post" action="/mark/add/">
                    {% csrf_token %}
                    {{ fm.form.subject }}
                    {{ fm.form.assignment }}
                    {{ fm.form.student }}
                    {{ fm.form.value }}
                    <button type="submit" style="alignment: right">
                      <i class="fa fa-save"></i>
                    </button>
                  </form>
                {% endif %}
              </td>
            {% endfor %}
          </tr>
        {% endfor %}
      </table>
    </div>
  {% endfor %}
{% endblock %}